module.exports={
    paths:{
        "javascript":"./src/javascripts/",
        "style":"./src/css/",
        "html":"./src/",
        "scss":"./src/scss"
    },
    proxyList:{
        "dt":"https://www.duitang.com/napi/index/hot/"
    }
}